#!/bin/bash

if [ ! -f ".env" ]; then
  if [ -f ".env.example" ]; then
    cp ".env.example" ".env"
  fi
fi
source .env

help(){
  echo "Usage: $0 [option]"
    echo "RUN:"
    echo "    func                  run function by name"
    echo "    start                 start demon by name"
    echo "    install               install packages"
    echo "    add                   add package to npm"
}

case "$1" in
  build) docker image rm ${IMAGE}:old; docker tag ${IMAGE} ${IMAGE}:old; docker build --build-arg BASE_IMAGE=${BASE_IMAGE} -t $IMAGE . ;;
  run) docker run -p 1111:1880 -d -e NODE_RED_ENABLE_PROJECTS=true -e THEME=${THEME}  -v .:/data \
    --name ${NAME} ${IMAGE} ;;
  flush) $0 build; $0 kill; $0 run; $0 log ;;
  log) docker logs -f ${NAME} ;;
  kill) docker kill ${NAME}; docker rm ${NAME} ;;
  help) help;; 
  --help) help ;; 
  *) echo "Invalid option: $1"; echo "Try '$0 --help' for more information."; help; exit 1;  ;;
esac